### ISSUE TITLE
Add mark as important task button?

### ISSUE THREAD

**Issue by PRA-developer-TIK** [varunherlekar/lets-do-it#15]
Hey can you asssign this issue to me ??I  loved the UI and wanted to add a few functionalities so may I??@varunherlekar

**Comment by varunherlekar** [comment]
Sure @PRA-developer-TIK

**Comment by ankitgauri26** [comment]
@varunherlekar  - As @PRA-developer-TIK is working on creating the button, let me know if I can work on the functionality. Like when any user clicks on important task button, the task border will be changed to some color or we can bold the text of the task.

**Comment by PRA-developer-TIK** [comment]
Thnx @varunherlekar  on it!!!

**Comment by varunherlekar** [comment]
No worries guys, @ankitgauri26 you can suggest some more improvements.

**Comment by ankitgauri26** [comment]
@varunherlekar  - Below are some of the recommendations
=>We can store the to-do's in local storage so that it will show all the previously created task even if the user closes the browser or refreshes the page.
=> We can add drag and drop functionality to move the task from in-progress to completed.
=>We can always show the important task first and then other task below it. Its like adding pin functionality
=> We can also show the time on which user added or updated the task
=> Replace edit, delete and mark as completed button to icons
=> We can give option to change bg color of the task  to group for specific category.
=> We can give option to sort the tasks

**Comment by varunherlekar** [comment]
Yes @ankitgauri26, Amazing ideas. Please create issues of whatever you can work on.

**Comment by ankitgauri26** [comment]
@varunherlekar - I am totally new to this Github world and not sure how to create issues and tag it with hactoberfest. Also not sure if I create a issue, assign it to myself and then raise PR will gets included in my hactoberfest participation or not. I'll be grateful if you can create those issues and assign it to me for now. I can work on some of them and also assign to others for Hactoberfest for their participation. Hope you'll understand and will give opportunity to work on this project :)

**Comment by varunherlekar** [comment]
You can directly raise PRs. There is no need to mention the issue. Just add the proper title to PR. It will work for Hacktober fest

**Comment by varunherlekar** [comment]
You can directly raise PRs. There is no need to mention or create the issue. Just add the proper title to PR. It will work for Hacktober fest. This repo has Hacktober fest label so every valid PR will be considered for this event.
